services:
  - type: web
    name: telewater
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m telewater
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
